### 쿠폰 등록
POST http://localhost:10352/coupons/policy
Content-Type: application/json

{
  "couponName": "가입 축하 10% 할인 (최대 5천원)",
  "couponDiscountType": "PERCENT",
  "couponDiscountAmount": 10,
  "couponMinimumOrderAmount": 50000,
  "couponMaximumDiscountAmount": 10000,
  "couponScope": "ALL",
  "couponExpiredAt": "2025-12-31T23:59:59",
  "couponIssuePeriod": null,
  "bookIds": [],
  "categoryIds": [],
  "couponType": "WELCOME"
}


### 2번째 쿠폰 등록
POST http://localhost:10352/coupons/policy
Content-Type: application/json

{
  "couponName": "2만원 이상 구매 시 3천원 할인",
  "couponDiscountType": "AMOUNT",
  "couponDiscountAmount": 3000,
  "couponMinimumOrderAmount": 20000,
  "couponMaximumDiscountAmount": null,
  "couponScope": "ALL",
  "couponExpiredAt": "2025-12-31T23:59:59",
  "couponIssuePeriod": null,
  "bookIds": [],
  "categoryIds": [],
  "couponType": "GENERAL"
}

### 3번째 쿠폰 등록
POST http://localhost:10352/coupons/policy
Content-Type: application/json

{
  "couponName": "가입 축하 1만원 할인 쿠폰",
  "couponDiscountType": "AMOUNT",
  "couponDiscountAmount": 10000,
  "couponMinimumOrderAmount": 50000,
  "couponMaximumDiscountAmount": null,
  "couponScope": "ALL",
  "couponExpiredAt": "2025-12-31T23:59:59",
  "couponIssuePeriod": 30,
  "bookIds": [],
  "categoryIds": []
}

### 도서 부분 쿠폰 등록
POST http://localhost:10352/coupons/policy
Content-Type: application/json

{
  "couponName": "특정 도서 5천원 할인",
  "couponDiscountType": "AMOUNT",
  "couponDiscountAmount": 5000,
  "couponMinimumOrderAmount": 15000,
  "couponMaximumDiscountAmount": null,
  "couponScope": "BOOK",
  "couponExpiredAt": "2025-12-31T23:59:59",
  "couponIssuePeriod": null,
  "bookIds": [10, 25, 30],
  "categoryIds": []
}

### 카테고리 부분 쿠폰 등록
POST http://localhost:10352/coupons/policy
Content-Type: application/json

{
  "couponName": "특정 도서 5천원 할인",
  "couponDiscountType": "AMOUNT",
  "couponDiscountAmount": 5000,
  "couponMinimumOrderAmount": 15000,
  "couponMaximumDiscountAmount": null,
  "couponScope": "CATEGORY",
  "couponExpiredAt": "2025-12-31T23:59:59",
  "couponIssuePeriod": null,
  "bookIds": [],
  "categoryIds": [1, 2, 3]
}


### 생일 쿠폰 등록
POST http://localhost:10352/coupons/policy
Content-Type: application/json

{
  "couponName": "Birthday Coupon",
  "couponDiscountType": "PERCENT",
  "couponDiscountAmount": 15,
  "couponMinimumOrderAmount": 10000,
  "couponMaximumDiscountAmount": 10000,
  "couponScope": "ALL",
  "couponExpiredAt": null,
  "couponIssuePeriod": 30,
  "bookIds": [],
  "categoryIds": [],
  "couponType": "BIRTHDAY"

}

### 웰컴 쿠폰 정책 등록
POST http://localhost:10352/coupons/policy
Content-Type: application/json

{
  "couponName": "Welcome Coupon",
  "couponDiscountType": "PERCENT",
  "couponDiscountAmount": 10,
  "couponMinimumOrderAmount": 5000,
  "couponMaximumDiscountAmount": 5000,
  "couponScope": "ALL",
  "couponExpiredAt": null,
  "couponIssuePeriod": 30,
  "bookIds": [],
  "categoryIds": []
}

### 사용자에게 쿠폰 발급
POST http://localhost:10352/coupons/users/11/issue/1
Content-Type: application/json

### 사용자에게 생일 쿠폰 발급
POST http://localhost:10352/coupons/users/7/issue-birthday?birthMonth=4
Content-Type: application/json

### 사용자에게 웰컴 쿠폰 발급
POST http://localhost:10352/coupons/users/9/issue-welcome
Content-Type: application/json




### 사용자 활성 쿠폰 조회
GET http://localhost:10352/coupons/users/1/active
Content-Type: application/json


### 사용자 사용된 쿠폰 조회
GET http://localhost:10352/coupons/users/1/used
Content-Type: application/json


### 사용자 쿠폰 사용
POST http://localhost:10352/coupons/users/1/use/4
Content-Type: application/json

{
  "orderId": 25623
}


### 할인 금액 계산 (기본)
GET http://localhost:10352/coupons/users/1/calculate-discount/3?orderAmount=50000
Content-Type: application/json

### 할인 금액 계산 (특정 도서 포함)
GET http://localhost:10352/coupons/users/1/calculate-discount/3?orderAmount=30000&bookIds=10
Content-Type: application/json

### 할인 금액 계산 (특정 카테고리 포함)
GET http://localhost:10352/coupons/users/1/calculate-discount/3?orderAmount=30000&categoryIds=101
Content-Type: application/json