# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Coupon API CI with Maven # ** 변경: 워크플로우 이름 명확히 변경 **

on:
  push:
    branches: [ "develop" ] 
    paths: 
      - 'bookstore-coupon-api/**'
      - '.github/workflows/coupon-api-ci.yml' 

  pull_request:
    branches: [ "develop" ]
    paths: 
      - 'bookstore-coupon-api/**'
      - '.github/workflows/coupon-api-ci.yml'

permissions:
  contents: write 
  actions: read
  security-events: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Set up JDK 21 
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    - name: Build with Maven 
      run: mvn -B package -f bookstore-coupon-api/pom.xml 

    - name: Run SonarQube 
      run: |
        mvn clean verify sonar:sonar \
          -Dsonar.projectKey=bookstore-BeanSolid-coupon-api `# ** 변경: 쿠폰 API의 고유한 프로젝트 키로 변경 **` \
          -Dsonar.projectName='bookstore-BeanSolid-coupon-api' `# ** 변경: 쿠폰 API의 프로젝트 이름으로 변경 **` \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -f bookstore-coupon-api/pom.xml `# ** 변경: 쿠폰 API의 pom.xml 경로 지정 **`

    - name: Upload Coupon API Jar
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "bookstore-coupon-api/target/*.jar" 
        target: "~/jars/coupon-api"
        strip_components: 1
        rm: false

    - name: Execute Coupon API Startup Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: "~/sh/coupon-api_startup.sh" 
